# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBTaskBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuan_id', models.IntegerField(verbose_name='远景ID')),
                ('yuan_photos', models.CharField(max_length=1000, verbose_name='远景图片')),
                ('san_taskid', models.CharField(max_length=30, verbose_name='三高taskid')),
                ('address', models.CharField(max_length=400, verbose_name='地址')),
                ('event_content', models.CharField(max_length=300, verbose_name='时间内容')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
