# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0002_tbtaskbridge_yuan_eventnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='yuan_id',
            field=models.CharField(max_length=20, verbose_name='远景ID'),
        ),
    ]
