# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0003_auto_20180610_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtaskbridge',
            name='yuan_occurredStr',
            field=models.DateField(max_length=20, null=True, verbose_name='检查日期'),
        ),
    ]
