# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0004_tbtaskbridge_yuan_occurredstr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtaskbridge',
            name='yuan_status',
            field=models.IntegerField(choices=[(0, 'XXX'), (2, '通过'), (4, '挂起')], default=0, verbose_name='状态码'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='导入时间'),
        ),
    ]
