# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0005_auto_20180611_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='event_content',
            field=models.CharField(max_length=300, verbose_name='事件内容'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='san_taskid',
            field=models.CharField(blank=True, max_length=30, verbose_name='三高taskid'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='status',
            field=models.IntegerField(choices=[(0, '初始状态'), (1, '进入网格化')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='yuan_status',
            field=models.IntegerField(choices=[(0, '新增'), (1, '回复'), (2, '通过'), (3, '退回'), (4, '挂起'), (6, '争议'), (7, '撤销')], default=0, verbose_name='远景系统状态'),
        ),
    ]
