# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 22:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0006_auto_20180618_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtaskbridge',
            name='loc',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='经纬度'),
        ),
    ]
