# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0007_tbtaskbridge_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtaskbridge',
            name='district',
            field=models.IntegerField(choices=[(0, '徐静'), (1, '赵项')], default=0, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='tbtaskbridge',
            name='san_status',
            field=models.IntegerField(choices=[(0, '待受理'), (1, '待核实'), (2, '已上报核实'), (3, '待立案'), (4, '待派遣'), (5, '待催办'), (6, '待下发核查'), (7, '已下发核查'), (8, '待结案'), (9, '已结案'), (10, '已作废'), (11, '已退回其他平台'), (12, '待收集'), (13, '不受理'), (14, '已受理'), (15, '已立案'), (15, '已派遣')], default=0, verbose_name='网格化状态'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='status',
            field=models.IntegerField(choices=[(0, '初始状态'), (1, '进入网格化'), (2, '地址需要整理')], default=0, verbose_name='状态'),
        ),
    ]
