# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0008_auto_20180620_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtaskbridge',
            name='san_remark',
            field=models.CharField(blank=True, max_length=700, verbose_name='三高回复'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='district',
            field=models.IntegerField(choices=[(0, '徐泾'), (1, '赵巷'), (2, '夏阳'), (3, '朱家角')], default=0, verbose_name='区域'),
        ),
    ]
