# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhongbo', '0009_auto_20180626_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbtaskbridge',
            name='san_image',
            field=models.TextField(blank=True, verbose_name='网格化图片'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='san_remark',
            field=models.CharField(blank=True, max_length=700, verbose_name='网格化回复'),
        ),
        migrations.AlterField(
            model_name='tbtaskbridge',
            name='san_taskid',
            field=models.CharField(blank=True, max_length=30, verbose_name='网格化任务号'),
        ),
    ]
